LIGHT_CONSUMPTION = 5
AC_CONSUMPTION = 10
STATUS = {1 => 'ON', 0 => 'OFF'}
MOVEMENT_TYPE =  { movement: 1, no_movement: 0}
MAIN_CORRIDOR_INITIAL_CONSUMPTION = 15
SUB_CORRIDOR_INITIAL_CONSUMPTION = 10
